os:
  - linux

dist: trusty

language: c

cache:
  directories:
    - "$HOME/.nimble"
    - "$HOME/.choosenim"

install:
  - export CHOOSENIM_CHOOSE_VERSION="1.2.0"
  - |
      curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      sh init.sh -y
before_script:
  - set -e
  - set -x
  - export PATH=$HOME/.nimble/bin:$PATH
  - export CHOOSENIM_NO_ANALYTICS=1

script:
  - nimble test